### ISSUE TITLE
Complete capabilitystatement resources

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/provider-directory#1]
complete capabilitystatement resources - 

The server needs all the search criteria added and the bit about includes

Update the narrative for a prettier, more complete display.  There is a transform that Lloyd has that creates the nice narrative in the FHIR build source directory.  (Need to update to 'CapabilityStatement'  though.

**Comment by brettmarquard** [comment]
Drafted, need to review narratives

**Comment by brettmarquard** [comment]
completed
