### ISSUE TITLE
No PractitionerRole search param for endpoint reference

### ISSUE THREAD

**Issue by Healthedata1** [argonautproject/provider-directory#2]
see GFORGE [#12344]

unable to do a search such as:

`Get http://fhir3.healthintersections.com.au/open/PractitionerRole?specialty:text=cardio&_include=PractitionerRole:patient&_include=PractitionerRole:organization&_include=PractitionerRole:endpoint`

to retrieve all resource in a bundle.

**Comment by brettmarquard** [comment]
resolve with broader ticket [#12363](http://gforge.hl7.org/gf/project/fhir/tracker/?action=TrackerItemEdit&tracker_item_id=12363&start=0)

**Comment by brettmarquard** [comment]
pre-applied
