### ISSUE TITLE
Update all references/links to final home

### ISSUE THREAD

**Issue by brettmarquard** [argonautproject/provider-directory#5]

**Comment by Healthedata1** [comment]
I updated:

-  path to the main FHIR specification (defined in ig.json)- {{ site.data.fhir.path }} = http://build.fhir.org
- canonical : canonical path to this specification (defined in ig.json)- {{ site.data.fhir.canonical }} in all non spreadsheet locations.

**Comment by Healthedata1** [comment]
done
