### ISSUE TITLE
Add Org example on Home

### ISSUE THREAD

**Issue by ncnuech** [argonautproject/provider-directory#7]
Can we add an example search for Organization on the Home page?

I don't think its explicitly clear what data we would receive/the purpose of querying for an organization.

**Comment by brettmarquard** [comment]
The expected queries a server should support are listed on the [profile pages](http://build.fhir.org/ig/argonautproject/provider-directory/StructureDefinition-argo-organization.html)

**Comment by brettmarquard** [comment]
please let me know if you are unable to locate
