### ISSUE TITLE
PractitionerRole requirement summaries don't match

### ISSUE THREAD

**Issue by smater** [argonautproject/provider-directory#9]
![image](https://cloud.githubusercontent.com/assets/3189464/25360447/c76f72c2-290e-11e7-8831-acfdbf9eff31.png)

![image](https://cloud.githubusercontent.com/assets/3189464/25360459/d00675ca-290e-11e7-89be-f757293c5b64.png)

**Comment by brettmarquard** [comment]
fixed, thanks
